### ISSUE TITLE
field `extensions` of struct `LoaderConfig` is private

### ISSUE THREAD

**Issue by quanhuanhuan** [ZettaScaleLabs/zenoh-flow-examples#1]
executing command   ”cargo build --release -p runtime “  error
error[E0451]: field `extensions` of struct `LoaderConfig` is private
  --> runtime/src/main.rs:59:32
   |
59 |         None => LoaderConfig { extensions: vec![] },
   |                                ^^^^^^^^^^^^^^^^^^ private field

For more information about this error, try `rustc --explain E0451`.
error: could not compile `runtime` due to previous error

**Comment by gabrik** [comment]
Fixed in https://github.com/ZettaScaleLabs/zenoh-flow-examples/commit/aafed5d631e32df5fbfeecd7727ff94a2e62b39a
